# Generated by Django 5.2.4 on 2025-10-08 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=200, verbose_name='商品名')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='ブランド')),
                ('color_code', models.CharField(blank=True, max_length=50, verbose_name='色番/カラー')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='画像URL')),
                ('opened_on', models.DateField(verbose_name='開封日')),
                ('expires_on', models.DateField(verbose_name='使用期限')),
                ('expires_overridden', models.BooleanField(default=False, verbose_name='期限手動上書き')),
                ('status', models.CharField(choices=[('using', '使用中'), ('finished', '使用済み')], default='using', max_length=10, verbose_name='ステータス')),
                ('finished_at', models.DateField(blank=True, null=True, verbose_name='使用終了日')),
                ('risk_flag', models.CharField(blank=True, choices=[('low', '低'), ('mid', '中'), ('high', '高')], max_length=10, verbose_name='期限リスク')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'アイテム',
                'verbose_name_plural': 'アイテム',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('type', models.CharField(choices=[('D30', '30日前'), ('D14', '14日前'), ('D7', '7日前'), ('OVERWEEK', '期限切れ')], max_length=10, verbose_name='通知種別')),
                ('title', models.CharField(max_length=200, verbose_name='通知タイトル')),
                ('body', models.TextField(verbose_name='通知本文')),
                ('scheduled_for', models.DateTimeField(verbose_name='通知予定時刻')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='既読時刻')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beauty.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
                ('depth', models.IntegerField(default=0, verbose_name='階層レベル')),
                ('full_path', models.CharField(blank=True, max_length=300, verbose_name='フルパス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='beauty.taxon', verbose_name='親カテゴリ')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
                'ordering': ['depth', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LlmSuggestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('target', models.CharField(choices=[('category', 'カテゴリ'), ('product_name', '商品名'), ('brand', 'ブランド')], max_length=20, verbose_name='推定対象')),
                ('suggested_text', models.TextField(verbose_name='LLM推定テキスト')),
                ('accepted', models.BooleanField(default=False, verbose_name='採用')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beauty.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chosen_taxon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_choices', to='beauty.taxon', verbose_name='選択カテゴリ')),
                ('suggested_taxon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_suggestions', to='beauty.taxon', verbose_name='推定カテゴリ')),
            ],
            options={
                'verbose_name': 'LLM提案ログ',
                'verbose_name_plural': 'LLM提案ログ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='product_type',
            field=models.ForeignKey(help_text='最も詳細なカテゴリを選択してください', on_delete=django.db.models.deletion.CASCADE, to='beauty.taxon', verbose_name='商品カテゴリ'),
        ),
    ]
