# Generated by Django 5.2.7 on 2025-10-04 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.TextField(unique=True, verbose_name='カテゴリ名')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.TextField(unique=True, verbose_name='形状名')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shapes', to='beauty.category', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '形状',
                'verbose_name_plural': '形状',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.TextField(db_index=True, verbose_name='商品名')),
                ('brand', models.TextField(blank=True, db_index=True, null=True, verbose_name='ブランド')),
                ('color_code', models.TextField(blank=True, null=True, verbose_name='色番/カラー')),
                ('image_url', models.TextField(blank=True, null=True, verbose_name='画像URL')),
                ('opened_on', models.DateField(db_index=True, verbose_name='開封日')),
                ('expires_on', models.DateField(db_index=True, verbose_name='消費期限日')),
                ('expires_overridden', models.BooleanField(default=False, verbose_name='期限手動上書き')),
                ('status', models.TextField(choices=[('using', '使用中'), ('finished', '使用済み')], db_index=True, default='using', verbose_name='ステータス')),
                ('finished_at', models.DateField(blank=True, null=True, verbose_name='使用終了日')),
                ('risk_flag', models.TextField(blank=True, choices=[('low', '低'), ('mid', '中'), ('high', '高')], db_index=True, null=True, verbose_name='期限リスク')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='beauty.category', verbose_name='カテゴリ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('shape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='beauty.shape', verbose_name='形状')),
            ],
            options={
                'verbose_name': 'アイテム',
                'verbose_name_plural': 'アイテム',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LlmSuggestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField(choices=[('category', 'カテゴリ'), ('shape', '形状'), ('advice', 'アドバイス')], db_index=True, verbose_name='提案対象')),
                ('accepted', models.BooleanField(default=False, verbose_name='採用/却下')),
                ('chosen_value', models.TextField(blank=True, null=True, verbose_name='採用した値')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_suggestion_logs', to='beauty.item', verbose_name='アイテム')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_suggestion_logs', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'LLM提案ログ',
                'verbose_name_plural': 'LLM提案ログ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'target'], name='beauty_llms_user_id_c0d151_idx'), models.Index(fields=['user', 'accepted'], name='beauty_llms_user_id_039b39_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('D30', '30日前通知'), ('D14', '14日前通知'), ('D7', '7日前通知'), ('OVERWEEK', '期限超過週次通知')], db_index=True, verbose_name='通知種別')),
                ('title', models.TextField(verbose_name='通知タイトル')),
                ('body', models.TextField(verbose_name='通知本文')),
                ('scheduled_for', models.DateTimeField(db_index=True, verbose_name='通知予定時刻')),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='既読時刻')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='beauty.item', verbose_name='アイテム')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-scheduled_for'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='beauty_noti_user_id_e5e771_idx'), models.Index(fields=['user', 'scheduled_for'], name='beauty_noti_user_id_a4eb41_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['user', 'status'], name='beauty_item_user_id_ab3a21_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['user', 'expires_on'], name='beauty_item_user_id_82c6b6_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['user', 'risk_flag'], name='beauty_item_user_id_751359_idx'),
        ),
    ]
