# Generated by Django 5.2.4 on 2025-10-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='shelf_life_anchor',
            field=models.CharField(choices=[('same_day', '同じ日付'), ('end_of_month', '月末')], default='end_of_month', help_text='月末で締めるか、同日で締めるかを指定します。', max_length=12, verbose_name='期限の基準日'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='shelf_life_months',
            field=models.PositiveIntegerField(default=6, help_text='開封から何か月後に使用期限となるかを設定します。', verbose_name='使用期限（月数）'),
        ),
    ]
